/**
 * NarrativeBlock.jsx
 *
 * Renders the plain-language narrative summary generated by the orchestrator's
 * SYNTHESIZE stage. This is the "analyst memo" — prose that explains the
 * diagnosis in business terms, not data terms.
 *
 * The text prop may contain HTML markup (e.g. <strong>, <em>, <ul>) because the
 * orchestrator produces lightly formatted output. We render it via
 * dangerouslySetInnerHTML, which is safe here because:
 *   1. The content comes from fixture data (controlled static JSON files), not user input.
 *   2. When the real backend is wired up, the FastAPI layer will sanitize LLM output
 *      before it reaches this component.
 *
 * Props:
 *   text {string} — HTML string containing the narrative. May include inline tags
 *                   like <strong>, <em>, and simple block tags like <p>.
 *
 * Example:
 *   <NarrativeBlock text="<p>Click Quality dropped <strong>3.2pp</strong> week-over-week...</p>" />
 */
export default function NarrativeBlock({ text }) {
  return (
    <div>
      {/* Section header — sits ABOVE the card per design convention */}
      <div
        className="text-xs font-semibold uppercase tracking-wider mb-2"
        style={{ color: 'var(--text-muted)', fontFamily: "'Fira Sans', sans-serif" }}
      >
        Summary
      </div>

      <div
        className="p-4 rounded-lg border"
        style={{
          background: 'var(--bg-card)',
          borderColor: 'var(--border)',
          fontFamily: "'Fira Sans', sans-serif",
          lineHeight: '1.7'
        }}
      >
        {/* dangerouslySetInnerHTML is intentional — see JSDoc above for safety rationale */}
        <div
          className="text-sm"
          style={{ color: 'var(--text-secondary)' }}
          dangerouslySetInnerHTML={{ __html: text }}
        />
      </div>
    </div>
  )
}
